# SPDX-FileCopyrightText: 2022 Alvar Penning
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

jobs:
  golang:
    name: Check Go code

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.17', '1.19' ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - run: go version

    - run: go build ./...

    - run: go test -v ./geohash/...

    - uses: golangci/golangci-lint-action@v3
      with:
        skip-pkg-cache: true
        skip-build-cache: true

  reuse:
    name: Check REUSE compliance

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: fsfe/reuse-action@v1

